baseURL = "https://teddythewriter.github.io/teddywrites/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "teddywrites"

title = 'teddywrites'

[languages.en.params]
  homeSubtitle = "If I were to write everything that's in my mind, I'd lose it quite easily."

locale = "en-US"

pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10

copyright = "teddywrites"
enableEmoji = true

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[params.author]
  name = "Teddy"
  about = "about"

[taxonomies]
  tag = "tags"

[related]
  includeNewer = true
  threshold = 70
  toLower = true

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10

[params]
  description = "Short fiction, personal reflections, and fragments by Teddy."
  images = ["og.png"]

  [params.assets]
    favicon = "favicon-96x96.png"

  [params.schema]
    publisherType = "Person"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20

  [[menu.main]]
    name = "Explore"
    url = "tags/"
    weight = 15
